### ISSUE TITLE
Add back missing Local Development content

### ISSUE THREAD

**Issue by ClaytonFarr** [boostercloud/booster#1001]
## Description

While searching if it was possible to set a custom port for the local environment I came across this content in an earlier version of the docs - 

https://github.com/boostercloud/booster/pull/243/files/53e9debf9a4311705dc596d9c18733c790d2129b#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R1965-R2044

It includes helpful details for how to work with the local development environment (port config, /auth, /graphql endpoints, etc) that I'm guessing were accidentally lost when the docs were moved from a single read me to separate documents.

**Comment by vukgogo** [comment]
@ClaytonFarr I might be blind, but I believe the local auth feature might have been scrapped from the latest version of Booster?
