### ISSUE TITLE
Create a CLI command to create a new rocket

### ISSUE THREAD

**Issue by jesusAlvSoto** [boostercloud/booster#1008]
## Description
Creating a new rocket is a tedious process. It would be nice to automate this process as much as possible.

## Possible Solution
Create a CLI command that creates the file structure for a new rocket, setting up lerna, linter files, etc. For instance:

`$ boost new:rocket awesome-rocket-name`

**Comment by AdrianLorenzoDev** [comment]
This issue is a duplicate of #644. I would close the old one or merge it with this one @jesusAlvSoto :)

**Comment by jesusAlvSoto** [comment]
Closing this issue as it is a duplicate of https://github.com/boostercloud/booster/issues/644
