### ISSUE TITLE
Use Array<UUID> field as joinKey in Read Model projection annotation

### ISSUE THREAD

**Issue by damagode** [boostercloud/booster#1053]
## Description

Sometimes I need to use an Array of UUIDs as `joinKey` in Read Model Projections. This is not supported right now and I think it could be a great addition. 

In my mind, the wanted behavior would be to apply the same projection to all of the ids inside the array. 

Something like:

_Entity:_
```
array: [id1, id2]
```

_Projection:_
```
@Projects(Entity, 'array')
```

_Behavior:_
```
Projection logic applied to Read Model with id1
Projection logic applied to Read Model with id2
```

## Possible Solution

In `ReadModelStore` class, we can make the `joinKeyForProjection` to return an array and apply the projection logic to all of the elements individually.

**Comment by javiertoledo** [comment]
Closing, as it's done and merged 🚀
