### ISSUE TITLE
[CLI] Allow a parameter to run the new:project command with default values

### ISSUE THREAD

**Issue by itrion** [boostercloud/booster#115]
It would be great to have a parameter like `-y` in the `project:new` command so when we run 

```shell
boost project:new my-boosted-project -y
```
The CLI doesn't ask the user for inputs and everything is created with default values

**Current behavior**

```shell
> boost new:project my-boosted-project
? What's your project description? (default: "") 
> Intro
? What's the first version? (default: 0.1.0) 
> Intro
? Who's the author? (default: "") 
> Intro
? What's the website? (default: "") 
> Intro
? What license will you be publishing this under? (default: MIT) 
> Intro
? What's the URL of the repository? (default: "") 
> Intro
? What's the package name of your provider infrastructure library?
> Intro
(AWS)
ℹ boost new 🚧
✔ Creating project root
✔ Generating config files
✔ Installing dependencies
ℹ Project generated!
```

**expected behavior**
```shell
> boost new:project my-boosted-project -y
ℹ boost new 🚧
✔ Creating project root
✔ Generating config files
✔ Installing dependencies
ℹ Project generated!
```

I propose `-y` because that's kind of standard in CLIs for `yes to all`

**Comment by MYF95** [comment]
The only thing I can't see as a default is the infrastructure provider. I'm guessing as of now this could work since we don't have any other provider. Would it make sense to integrate this knowing we would have to change it later on?

**Comment by itrion** [comment]
@MYF95, I think it makes to keep AWS as the default provider. I could bet it will be the default for long, just because it is the platform we have invested more energy, so it plays with an advantage over the others.

Once we have more providers in place, we can force the user to set a provider when running the command using `-y`

Like:

```text
> boost new:project my-project -y
Error: when using -y you have to set a provider using the -p argument
```

so you would need to run:

```text
boost new:project my-project -y -p aws
```

**Comment by MYF95** [comment]
That makes sense, in that case I would also like this feature since creating a new project I always use the default values.

Although now that I'm thinking, would it make sense to have the `-y` flag activated by default? To make it as easy as possible to start using it, I think it would be worth considering to have the following flow:

```
> boost new:project my-project
ℹ boost new 🚧
✔ Creating project root
✔ Generating config files
✔ Installing dependencies
ℹ Project generated!
```
and rather have flags in case you want to add extra config, like, complete setup
```
> boost new:project my-project -a
... have the current flow here
```
(I'm not really sure what the usual command in console would be as an extra config flag)

I think most of the information that is provided at the beginning should be easy to change, mainly through the `package.json`, unless it is not, in which case this idea wouldn't make much sense.

**Comment by javiertoledo** [comment]
Actually, why not always generating the project with the defaults? We can even set AWS as the default, as it's the only option that currently works. If you want to use another provider, we can add a `--provider=xyz` option. This is how Rails does it and it works great, if you make a mistake, deleting the project and regenerating it with the right option is a relatively cheap operation. https://guides.rubyonrails.org/getting_started.html#creating-the-blog-application

**Comment by alvaroloes** [comment]
Ideally, when we had the `local provider`, it would make more sense to have that one by default
