### ISSUE TITLE
Rename `command` parameter to `input` in Command Handlers' template

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#1219]
# Bug Report

## Current Behavior

We're generating a command handler class whose `handle` has an argument called `command`. For new developers, this can be confusing, as in the GraphQL API the name of the argument for the command mutation is called `input`.

## Expected behavior

Ideally, the parameters are named equally, so its easier to grasp for a beginner.

## Possible Solution

Rename the parameter in the template

<details open>
<summary>Checklist</summary>

- [X] ``packages/cli/src/commands/new/command.ts`` ⚠️ No Changes Made
</details>

**Comment by themese** [comment]
Josema Fernandez here (not sure if I should be login in with a theam account).

I'm trying to make this simple change to get accostumed to the project. Are we talking here about file `@boostercloud/cli/src/templates/command.stub`? 
I was going to submit a quick PR but I don't have the rights yet

**Comment by javiertoledo** [comment]
It seems that this has been already resolved
