### ISSUE TITLE
Add support for notification events

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#1242]
## Description

Following up with the conversation in #894, we've found many scenarios whose implementation could be significantly simplified if we had support for notification events, that is, events that are not tied to any specific entity. The only thing these events can do is trigger an event handler that could potentially generate state change events to alter the state of some entities.

It could also make sense, as #894 suggests, to add support to reduce notification events directly from entities. Still, to ensure data consistency, it could be necessary to create separate state change events for each entity changed. However, this could be done implicitly by the framework to simplify the programming interface.

An especially interesting scenario that something like this could help to solve is broadcast events: An event that potentially alters the state of all entities of a specific type.

## Possible Solution

It'd be worth discussing options before committing to any particular solution.

**Comment by javiertoledo** [comment]
@rdiaz82 a couple of thoughts related to this:

A first iteration to solve this would be to decouple the events from the entities, so an event can exist without necessarily defining an entity ID or being reduced by an entity. Still, it would make sense to keep all events (state change and notification events) organized in topics and have some way of defining the partition key. At the end of the day, we could generalize events to be some data structure that has a **partition key** (user defined) and a **timestamp** (Automatically generated by Booster).

Seeing it in this way, a state change event (an event that is reduced by an entity) is just an event that happens to have a partition key that matches a pattern in the form `<entity name>-<entity id>`. If we want to have notification events, then we could decide how they're organized; for example, we could have a `topic` parameter in the data structure, but at the end of the day, a notification event is just an event with a partition key that doesn't match the previous pattern.

As they're essentially the same, it seems logical that we allow both scenarios by reusing the existing `@Event` decorator, but that makes it harder for the user to predict what happens if a user suddenly adds a reducer to one of their entities for a notification event (also adding the corresponding implementation of the `entityID` method). This would transform it into a state change event, and if they already have some of these events in the database, it might go unnoticed that they need to run a migration to include pre-existing events in the new entities state.

This makes me think that it would be worth fully separating state change events from notification events into two new decorators (I'd also remove the `entityID()` implementation requirement for state change events):

## State change events

```typescript
@StateChangeEvent // New decorator for StateChangeEvent (it will get the entity name from the reducer as usual)
export class PostCreated {
  public constructor(
    @entityID // New decorator to "mark" a field as the entity ID instead of defining a function. Defining this field would be required.
    readonly postId: UUID,
    readonly title: string,
    readonly content: string,
    readonly author: string
  ) {}
}

## Notification events

```typescript
@NotificationEvent
export class PostHasBeenUpdated {
  public constructor(
    @topic // Defines a topic that will be used as the partition key, there could be an alias called `partitionKey` that might be more "semantic" for some people
    readonly topic: string,
    readonly id: UUID,
    readonly postId: UUID
  ) {}
}
```

## Backwards compatibility

This is a huge change in the framework API but we don't want to wait until 2.0 to publish it, so it'd be important to keep backwards compatibility with the existing interface. To achieve this, we could make the `@Event` decorator an alias of the `@StateChange` event, and make the implementation of the `entityID` function optional (but checking that either the `entityID` method or the decorator are in place). We could mark these as deprecated and update the docs to encourage people to migrate to the new syntax, but keeping the old one until we move to 2.0.

What do you think?

**Comment by damienvieira** [comment]
@javiertoledo  Quick question, this one is about naming and not the solution itself.

Why calling the decorator _@StateChangeEvent_ and not _@StateEvent_?

It feels inconsistent, knowing that we are suggesting to call the new decorator _@NotificationEvent_ and not _@NotificationChangeEvent_ .

**Comment by damienvieira** [comment]
I think conceptually this would make more sense to me!

The decorator `@Event` and the newly added `@Notification` would be very clear. 
Also changing the `@Event` naming to something else could end up creating some confusion.
