### ISSUE TITLE
Adopt a standard documentation tool

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#1243]
## Description

The current project documentation has some issues with searches and links.

## Possible Solution

Adopt a widely used documentation tool like docusaurus.

**Comment by javiertoledo** [comment]
@BorjaZarco, what is missing to close this issue? Are there any pending tasks here?

**Comment by jesusAlvSoto** [comment]
@BorjaZarco can you please open a new issue describing what improvements you propose?
