### ISSUE TITLE
Seamless file uploads

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#1245]
## Description

We have two different rockets to handle file uploads in Booster:

* [Rocket File Uploads](https://github.com/boostercloud/rocket-file-uploads), the newer one, compatible for Azure and local providers
* [File Uploader Booster Rocket for AWS](https://github.com/boostercloud/rocket-fileuploader-aws-infrastructure), an older implementation for AWS

## Possible Solution

Add support for AWS to Rocket File Uploads and move it to the main monorepo or a new "official rockets" repository, and properly document it in the official documentation.

**Comment by jfsagasti** [comment]
The new version with AWS support was already published :)
