### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by fecony** [boostercloud/booster#1294]
# Bug Report
Cannot deploy to AWS because `boosted-blog-toolkit-bucket already exists`

## Current Behavior
I followed https://docs.boosterframework.com/getting-started/coding guide to build simple app and then deploy it to AWS. 

I created AWS account. 
Followed https://docs.boosterframework.com/getting-started/configuration#aws-provider-setup
Added credentials to `~/.aws/credentials`
After running `boost deploy -e production` it fails and creates empty stack

## Expected behavior

Happy stack in AWS with working `/graphql` endpoint and so on

## Additional information
Console logs
```
boost deploy -e production                                                                                                    [12:48:05]


ℹ boost deploy [production] 🚀
⠙ Deploying[Booster]|deploy:  Bootstraping the following environment: {"name":"Default environment","account":"421267864975","region":"eu-north-1"}
 ⏳  Bootstrapping environment aws://421267864975/eu-north-1...
⠇ Deployingboosted-blog-toolkit: creating CloudFormation changeset...
⠹ Deploying12:48:39 PM | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket
boosted-blog-toolkit-bucket already exists

 ❌  Environment aws://421267864975/eu-north-1 failed bootstrapping: Error: The stack named boosted-blog-toolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: boosted-blog-toolkit-bucket already exists
    at prepareAndExecuteChangeSet (/Users/richard/Code/boosted-blog/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/richard/Code/boosted-blog/node_modules/aws-cdk/lib/cdk-toolkit.ts:575:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/Users/richard/Code/boosted-blog/node_modules/aws-cdk/lib/cdk-toolkit.ts:572:5)
    at deploy (/Users/richard/Code/boosted-blog/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/deploy.js:17:5)
    at deploy (/Users/richard/Code/boosted-blog/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/index.js:11:35)
    at /usr/local/lib/node_modules/@boostercloud/cli/dist/common/script.js:30:13
✖ Deploying
    Error:  The stack named boosted-blog-toolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: boosted-blog-toolkit-bucket already
    exists
    (You can see the full error logs in ./errors.log)
```

Running `boost nuke` shows that bucket doesn't exist
<img width="940" alt="Screenshot 2023-01-07 at 12 52 03" src="https://user-images.githubusercontent.com/36774784/211146590-77175453-1067-40fa-8870-bafa1f07d768.png">

### Environment
@boostercloud/cli/1.3.5 darwin-x64 node-v19.2.0

- Booster version: 1.3.5
- Node/npm version: 19.2.0 | 8.19.3
- OS: OSX 13.1 (22C65)

**Comment by Fecony** [comment]
After renaming app to `blog-boosted` it did deploy 🤔 
`config.appName = 'blog-boosted'`
<img width="957" alt="Screenshot 2023-01-07 at 16 03 30" src="https://user-images.githubusercontent.com/36774784/211154670-6076cf68-be02-4988-b0a8-e336b7de6ab2.png">

**Comment by javiertoledo** [comment]
Hey @Fecony, thanks for pointing this out! S3 buckets require to have unique names in the entire AWS, so it might be possible that some other user has used this exact same bucket name for a different application (and that's why it works after renaming it). I'm not sure if we can easily detect this situation somehow to warn the user, but it could make sense to add a few extra semi-randomized characters to the bucket name to decrease the risk of collision, what does everyone else think @boostercloud/booster-core?

**Comment by Fecony** [comment]
@javiertoledo There was an issue for this
Didn't know that bucket names are shared
