### ISSUE TITLE
Improve documentations on providers

### ISSUE THREAD

**Issue by BorjaZarco** [boostercloud/booster#1323]
## Documentation improvement

There is room for improvement in our current documentation on Providers.

## Description

Booster currently supports the following providers:

- Local
- AWS
- Azure
- Kubernetes (May be deprecated)
- Custom provider

There are currently two sections in the docs that are dedicated to them. However, there is some room for improvement on both of them:

- [Provider configuration](https://docs.boosterframework.com/getting-started/configuration): This is part of the "getting started" section, it should include some basic documentation on providers so newcomers could easily run and deploy their application on their desired provider. This means that the subsections that need to be changed here are:

    - Local Provider: This is simple enough already, but feel free to make a revision of it
    - AWS: This may be OK too, however, it includes a section that might not belong here. The [multiple AWS environments](https://docs.boosterframework.com/getting-started/configuration#multiple-aws-environments) might be too complex for a getting started section, it could be moved to another section
    - Azure: There is information relevant to setting up this provider in the [going deep section](https://docs.boosterframework.com/going-deeper#azure-provider), such as setting env variables necessary for the deployment. 
    - Kubernetes: If it's going to be deprecated, we would need to mark it as such. 
    - Custom provider: We would need to add some info about it, saying that there is a possibility to create your own custom provider. But setup and info about it should be in another separate section as it may not be part of a quick "getting started" guide.

- [Going deeper with Booster](https://docs.boosterframework.com/going-deeper#configuration-and-environments): There is a subsection within this section where there is some info regarding providers. I believe that providers should have their own dedicated main section, such as:

```
Introduction
Getting Started
Booster Architecture
Features
Providers
├── Local
├── AWS
├── Azure
├── Custom provider
├── Kubernetes (May not be necessary if deprecated)
```

These dedicated sections should provide a deeper understanding of the providers. For example, some more complex configurations such as the multi-environment on AWS or the services used by each provider. 

> There was a table on the former documentation with every service used on each provided, this was not included in the new docs since it was deprecated and misleading. We could update it and split the table by services. You can check out the deprecated table [here](https://github.com/boostercloud/booster/blob/b248e9cb645237101381b99b4f7153113b02b887/docs/chapters/04_features.md#provider-feature-matrix)

> We could also include a calculator with the project's estimated costs for each provider. There is already one for [AWS](https://calculator.aws/#/estimate?id=bd6dbdf2986c1453df4a048d67d947072c1ed389) and [Azure](https://azure.com/e/e08a3c86bd7a439ea64c578d57dd8c80) providers

**Comment by javiertoledo** [comment]
Done in #1333
