### ISSUE TITLE
Step by step guides link is broken

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#1391]
## Description

Right under Getting Started > Build a Booster app in minutes

![image](https://user-images.githubusercontent.com/7448243/228907351-c900bbc5-b648-41a1-96ec-d2c02bdbbf80.png)

**Comment by twelve-von** [comment]
Hi,can you give me the correct link, I will replace the broken on with the correct one.
![image](https://user-images.githubusercontent.com/50107470/234016128-b49eff4f-1b1c-4518-8e32-9b057f32f24e.png)
the broken link is in the coding.mdx file

**Comment by yashp4858** [comment]
@NickSeagull hey! can I work on this issue
pls assign this to me

**Comment by yashp4858** [comment]
@NickSeagull also pls provide me with the correct link so I can replace it with the recent one
