### ISSUE TITLE
[CLI] `boost new:project` never ends on Windows

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#157]
When creating a new project on Windows, the `installing dependencies` never ends.

If we kill `boost` with `Ctrl + C`, we cannot perform an `npm install` inside the project, because `npm` is waiting for another `npm` instance to end.

Taking a look closely, a `node` process still appears on the Task Manager. This process is unkillable, as when executing

```powershell
# Forcefully kill all node.exe, including their children
taskkill /f /im node.exe /t
```

The command fails saying that the `node` process is attached to a parent process (the one we killed), and the only solution is to reboot in order to unlock `npm` and kill those `node` processes.

I suspect that we are doing something wrong when spawning the `npm` process. It'd be helpful to have #156 in order to debug this easier.

**Comment by Moneyba** [comment]
@NickSeagull do you know if this keeps happening?

**Comment by NickSeagull** [comment]
I'm not on a Windows machine anymore so cannot say, sorry

**Comment by jesusAlvSoto** [comment]
Closing this ticket as it has not received any comments in over a year. Please re-open it if you need it or find it useful
