### ISSUE TITLE
Suggestions for improvements (especially in docs)

### ISSUE THREAD

**Issue by JorgeRdg** [boostercloud/booster#21]
Hey everyone! I'm just starting with the framework, but I'm loving it so far. Congrats! :blush: 

When first using Booster, I thought I could just note down any kind of friction/bug/suggestion I could see. Hopefully, something of this will be useful for you. Please, take in mind these notes were taken a week ago (in case something has changed since).

1. Getting started doesn't include installation requirements (e.g. It seems like we need NPM. What Node+NPM versions are supported?)

2. Once everything's installed, the list of links to further follow is OK. But it would be better in my opinion to suggest a recommended next step (I'd personally link to the Cart example).

3. Installing dependencies takes some time and there's no feedback. I'd feel safer knowing what it's installing.

4. In Github's README step 7 for cart demo. Comments are longer than what the plugin shows in a 1080p resolution. We could just shorten those.

5. Cart entity ID field is not set as readonly by default when generated. Is this expected?

6. Samples show 'Projects' but that doesn't exist. Maybe it's `reduces` what it means?

7. Why not adding the imports in the samples? It seems like saving a few lines really makes it more difficult to know where some calls come from when implementing it on your own.

8. CartItem used in ReadModel, but defined as a private inner interface in Cart entity (can't be used directly)

9. "And thanks to the serverless foundation Booster is based on, you won't be paying anything if it is not used." <-- Is this right? I think that having some AWS resources set up will have like an idle cost, like Kinesis.

10. Deploy booster doesn't work because I didn't have AWS credentials set up. But the tool doesn't let you know that. Actually, I had to go through all the documentation to find out I had to create a `~/.aws/credentials` file. Again, this should probably be at the beginning of a get started tutorial, including what's required to do your first app.

11. Error when deploying: cart-demo already exists. We need to define a different unique name for it. What about randomizing the appname? Feels like something the tool could do on its own.

12. When showing the request examples in the docs, the way URLs are explained is difficult to follow. E.g.
> You need to do a GET request to the above URL followed by the readmodels/CartReadModel segment. 

What's _the above URL_? One would think it's the last URL formed, but it meant the root app URL. It'd be much simpler to just show exactly how the request would look like and stop cross-referencing.

**Comment by javiertoledo** [comment]
Thanks for your feedback! We'll make sure to include all these topics in our roadmap.

**Comment by javiertoledo** [comment]
Closing because these comments are from a very old version of the docs.
