### ISSUE TITLE
Typo in examples (@Projects annotation)

### ISSUE THREAD

**Issue by damagode** [boostercloud/booster#22]
Hi Team,

In the read model example the `@Projects` annotation is mistyped ( https://github.com/boostercloud/booster/blob/master/packages/framework-example/src/read-models/cart-read-model.ts#L17 ), I should be `@Projection` according to the definition ( https://github.com/boostercloud/booster/blob/master/packages/framework-core/src/decorators/projection.ts )

Thank you in advance

**Comment by alvaroloes** [comment]
Thanks David, but it is the other way around and the definition was already
fixed. If you take a look now at the file you linked, it is @Projects now
;-)

**Comment by damagode** [comment]
Thanks, I think it was a problem with my machine local dependency
