### ISSUE TITLE
Explore possibilities to have a custom index file for a specific provider

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#275]
For the Kubernetes provider, we need a specific index.ts file to configure all the express server to serve the Booster endpoints. At this moment we are hacking the deploy replacing the index.js before starting the application. We need to find a more elegant way to do this.

**Comment by jesusAlvSoto** [comment]
Closing this ticket as it has not received any comments in over a year. 
Please re-open it if you need it or find it useful.
