### ISSUE TITLE
Create `boost` command to allow creating/deleting/modifying users

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#296]
Right now, there is no way to create a user that has a role with the flag `allowSelfSignUp` to true.

Initially, we thought that a good way to create a user with those roles (or add those roles to an existing user) can be done with a CLI boost command.

Think if this is still a good approach and implement it.

Related issues
#284 https://github.com/boostercloud/booster/issues/290

**Comment by juanjoman** [comment]
WIP branch: https://github.com/boostercloud/booster/tree/users_cli_command

**Comment by javiertoledo** [comment]
We will remove auth from Booster's core soon, so I'll close this one
