### ISSUE TITLE
[TESTING TOOLS] Create a testing tools package to let developers easily create tests

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#301]
Create a testing tools package to let developers easily create tests.

**Comment by davidverdu** [comment]
Can we have more details for this issue implementation @boostercloud/booster-core ? Maybe creating an external repository with these testing functions? these functions should help programmer testing Booster abstractions?

**Comment by NickSeagull** [comment]
I think this fits more a discussion than an issue, as its more for brainstorming and coming up with ideas. Converting into a discussion
