### ISSUE TITLE
Check if we need to enable CORS in auth endpoints

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#311]
When working with PostWoman, I get CORS errors when trying to sign-up/in/out. But this is not the case for the GraphQL one. It'd be nice if we researched what is happening there

**Comment by MYF95** [comment]
Can confirm this error is happening on all endpoints @NickSeagull. It seems to be browser related, I tried to use those endpoints from my frontend page and it was also happening.

I've tried adding the `all origins` headers into the auth resources generated by booster in the `framework-aws-infrastructure` package to no avail. Changed from:
```
const authResource = this.apis.restAPI.root.addResource('auth')
```
to:
```
const authResource = this.apis.restAPI.root.addResource('auth', {
      defaultCorsPreflightOptions: {
        allowOrigins: Cors.ALL_ORIGINS,
      },
    })
```

Not sure if maybe I'm missing more headers (although the GraphQL endpoint only has this option added to it), but essentially frontend authentication is not feasible with the provided endpoints.

**Comment by MYF95** [comment]
FYI, using a proxy also works (or pages such as cors-anywhere), although I don't think it's ideal to depend on third party sites for this, especially for authentication.

**Comment by MYF95** [comment]
Would adding the userpool as an output when deploying booster be worthwhile in the meantime?

**Comment by itrion** [comment]
I'll close this ticket because the answer is: **yes, we need to enable CORS in the auth endpoints: `auth/sign-up`, `auth/sign-in`, and `auth/sign-out`.**

I'm going to open a ticket with a description of the problem and the work needed.
