### ISSUE TITLE
Local Provider: Entities projection into read models

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#317]
**Description**
The current local provider implementation is based on ExpressJS and the local document database nedb.

Implement the corresponding required methods from the ProviderInterface to make sure that new read models are projected and stored after every snapshot is processed in the corresponding tables in the nedb database. Tables should be generated automatically on the server startup.

**Acceptance criteria:**

* All the expected tables for the configured read models must be created when the server is started if they don’t exist.
* Every time that an event is processed, a new snapshot is generated, triggering the projection of the corresponding read models and storing their values in the right tables.
* Unit tests for the new/changed code.
* Integration and/or end-to-end tests that demonstrate that snapshots are projected into read models and stored in the corresponding tables.

**Comment by juanjoman** [comment]
I'm pausing this for now. Just in case someone picks up later, here's the current work, it should be missing tests only: https://github.com/boostercloud/booster/tree/i317-entities_projections_into_read_models. cc @itrion
