### ISSUE TITLE
Local Provider: Queries API

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#318]
The current local provider implementation is based on ExpressJS and the local document database nedb.

Implement the controllers and the corresponding required methods from the ProviderInterface to support GraphQL queries over Read Models.

**Acceptance criteria:**

- The system can process a GraphQL query and returns the corresponding data from the Read Models.
- Unit tests for the new/changed code.
- Integration and/or end-to-end tests that demonstrate that the query interface returns the data stored in the Read Models.

**Comment by NickSeagull** [comment]
Fixed by #473
