### ISSUE TITLE
Write documentation for Migrations

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#327]
As your application evolves, you might need to migrate some existing data to new versions, so your application can continue operating as normal. This migration needs to be documented so developers know what it needs to be done

**Acceptance criteria:**

- A guide on how-to migrate is written

- The migration information is added to the documentation project

- There are examples to migrate a Command, an Event, an Entity, and a ReadModel

**Comment by jesusAlvSoto** [comment]
We are in discussions about how to tackle migrations. Once it is clear we will open an issue(s) to describe what needs to be done and updating the documentation will be part of the issue(s).
