### ISSUE TITLE
Error while calling 'boost nuke'

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#341]
Submitted by @carlosper88 on Spectrum

> I'm getting this error while doing boost nuke. After setting the project name I get:

```
 ❌  red-button-booster-application-stack: deploy failed Error: AWS region must be configured either when you configure your CDK stack or through the environment
    at SDK.resolveEnvironment (/usr/local/lib/node_modules/@boostercloud/cli/node_modules/aws-cdk/lib/api/util/sdk.ts:168:13)
    at SDK.service (/usr/local/lib/node_modules/@boostercloud/cli/node_modules/aws-cdk/lib/api/util/sdk.ts:150:25)
    at Object.destroyStack (/usr/local/lib/node_modules/@boostercloud/cli/node_modules/aws-cdk/lib/api/deploy-stack.ts:228:15)
    at CdkToolkit.destroy (/usr/local/lib/node_modules/@boostercloud/cli/node_modules/aws-cdk/lib/cdk-toolkit.ts:195:9)
```

**Comment by NickSeagull** [comment]
Response by @alvaroloes 

> It seems the ./aws/credentials file was missing the region. Have you checked if this is happening with the latest Booster versions (c0.2.*)?

**Comment by NickSeagull** [comment]
Response by @glammers1 

> I just wanted to say that I don't have the region set in my /.aws/credentials file but in /.aws/config. See Setting the AWS Region section here https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

**Comment by NickSeagull** [comment]
Response by @MYF95 

> I'm having similar issues when I define the AWS_PROFILE environment variable. I use multiple aws credentials, but if I don't use the default one, it seems the region is not being detected. I have to manually export the AWS_REGION environment variable in that case. Currently using booster version 0.3.3

**Comment by NickSeagull** [comment]
Response by @MYF95 

> Testing some stuff out, it seems that ~/.aws/config is not being used correctly unless you're using the default profile.
If you set up export AWS_PROFILE=nonDefaultProfile, you need to declare the region in the ~/.aws/credentials file.

**Comment by jesusAlvSoto** [comment]
Closing this question/bug as it has not received any follow-up for a long time. 
The `boost nuke` command is currently working correctly.
