### ISSUE TITLE
Signing up process

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#342]
Submitted by @carlosper88 in Spectrum

> 1. Is it possible to disable the need for confirming the email?

> 2. Can the username be a string like, for example a phone or a nickname? I tried setting a string which was not an email and it returns an error

> The reason behind this, is to be able to integrate with Firebase, which already offers a sign-up method with OTP via email, phone, or whatever it is needed. Once we get to sign-up and sign-in against firebase, we would sign-up against booster and continue using our Booster backend.
Another possibility would be to use a unique booster user for all of the users, but we would lose the power of the register.currentUser while creating commands

**Comment by carlosper88** [comment]
@NickSeagull I'd close this one as this is a future feature ;)
