### ISSUE TITLE
Where in the code should one define roles?

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#343]
Submitted by @MarcAstr0 in Spectrum

> It's not explicitly stated in the docs, and there's no boost new command for roles, so I'm guessing it's up to the developer to define them wherever he wants, right?

**Comment by NickSeagull** [comment]
Response by @alvaroloes 

> Yes, there is no generator for roles yet (there will be). You can put all your role definitions in a file called roles.ts in the root of your project, for example. As long as the role class has the `@Role`  decorator, it doesn't matter where you put them, Booster will find them.

**Comment by NickSeagull** [comment]
Response by @carlosper88

> @marcastr0 In case you find it useful, this is how I added them

```
import { Role } from "@boostercloud/framework-core";
@Role({
    allowSelfSignUp: false
})
export class Admin {}
@Role({
    allowSelfSignUp: true
})
export class User {}
```

**Comment by jesusAlvSoto** [comment]
Closing this question as it has been answered and there has not been a follow-up for a long time. 
More information about **roles** can be found in the docs: https://docs.booster.cloud/chapters/04_features#authentication-and-authorization
