### ISSUE TITLE
Static Assets

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#346]
Submitted by @hcatlin on Spectrum

> I know that Booster is primarily a CQRS platform for backend systems... but as part of the theme is "make it easy to do cloud stuff"– has there been consideration to give a simple way to deploy static assets for SPAs? Like, support Gatsby or similar– just handle the S3 upload and standard configurations.

**Comment by NickSeagull** [comment]
Response by @alvaroloes 

> Yes, this already supported. Just put all your SPA resources in the <project root>/public/ folder and they will be uploaded to S3.
In fact, several things will happen:
Your resources will be uploaded to a private S3 bucket
A CloudFront web distribution is created in front of that bucket
A "static website URL" is generated so that you can access your SPA
Some things to consider:
You can see the URL to access your SPA after the deployment in the Outputs section, under the name staticWebsiteURL
Be sure you have a public/index.html file. It will be the root of your SPA
That's all. Let us know if this works for you

> Just FYI: The deployment time when having a public folder in your project will increase considerably (between 5 to 10 minutes) in AWS, as the CloudFront deployment takes long

**Comment by NickSeagull** [comment]
Response by @javiertoledo 

> Yes, right now this is pretty much handled as the public folder in a Rails app, whatever you put in there, will become available once the application is deployed (through that staticWebsiteURL), but we're not handling any frontend build processes at the moment. This is currently an open question that we've been avoiding, because the range of tools availale to produce SPAs or static sites seems too wide to make a "right decision" that works for everyone. For now, our recommendation would be that you keep the front-end project in a different folder and make your build tools compile the production assets to the public folder in the Booster project, but there might be better ways to solve this and provide a better developer experience. We're more than open to any ideas to improve this.

**Comment by jesusAlvSoto** [comment]
Closing this question as it has been answered and there has not been any follow-up for a long time.
