### ISSUE TITLE
Data Access?

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#347]
Submitted by @hcatlin on Spectrum

> So, let's say I launch on Booster and I have users signing up and they are posting content. I can see the content on the site and I'm like "YAY! Good work me! I wonder how many posts there have been? I wonder whose our most prolific user– I should totally reach out to them". Of course, I could answer these by putting in something like Amplitude or a whole Data Pipeline into an analytics package. Or, I could go build out a whole Stats API that recalculates these after every event just for my use. But even then, I've got a bootstrapping problem of not having had the data available already- so reacting to events it's hard to go back and re-issue all of the stats. I guess, my question is just around data handling, how to think of it, and how migrations/queries/rebuilds work?

**Comment by NickSeagull** [comment]
Response by @javiertoledo 

> While Booster is effectively event-driven and most of the processing is handled reactively, it also keeps all the events in the event store (which is basically an "infinite" DynamoDB table), so in theory, you'll always have access to the events history. The entities are a way to optimize reads generating snapshots representing the current state, and the read models (the data exposed to the read API) are projected from these snapshots to aggregate the data in any way that makes sense for you. Read Models are often just projecting entities 1 to 1, but you can also mix different entities or produce different views of the entities. The great advantage of event sourcing is that you gain some time-travel abilities, to see the state of the system in the past, fork an event store to play with it, or replay the events in different ways to be able to generate new views of the data, but we don't have specific tooling to do this in an easy way yet. The idea is to create tools that allow us to treat data as we manage code with git. Answering your questions:

> > I wonder how many posts there have been?

> If you create a PostReadModel exposing the Post entity, you can query it using GraphQL to get a list of all the posts that are available. I think that we don't have count operations or pagination yet in the GraphQL (@alvaroloes
 might know more about this than me), but you could create aggregations using a separate ReadModel as a workaround.

> > I wonder whose our most prolific user– I should totally reach out to them"

> This could be a bit tricky yet. One way to do this now is having a projection function in the UserReadModel (Or a different UserStatsReadModel that listens to the Post entities owned by a user and keep a counter of the interactions (every creation or update event). Read Models in a sense are reactive JOIN operations that can listen to different entities that share a field with the same semantics. For instance, in this example, we use the user id as the "join field" (which also becomes the read model id):

```
@ReadModel
export class UserReadModel {
    public constructor(readonly username: string, /* ...(other interesting fields from users)... */, readonly interactionCount: number) {}
    @Projects(User, 'id')
    public static projectUser(entity: User, current?: UserReadModel) {
      // Here we update the user fields
    }
    @Projects(Post, 'ownerId')
    public static projectPostInteraction(entity: Post, current?: UserReadModel) {
      current.interactionCount += 1 // This is likely a bad idea, it would be safer to keep the counter in the entity itself or a structure of the kind of interaction, but it works to show the idea.
    }
}
```

> With this projection in place, you should be able to use the GraphQL API to get the user with the highest interactionCount.
There's a lot that we can improve here yet, I think that it makes a lot of sense to have some easier ways to inspect and query the event store, but we haven't prioritized the tooling yet because, at the end of the day, the event store in AWS is just a long DynamoDB table, so it is relatively easy to inspect or query it with tools like Dynobase or the AWS console itself.


> > I've got a bootstrapping problem of not having had the data available already- so reacting to events it's hard to go back and re-issue all of the stats. I guess, my question is just around data handling, how to think of it, and how migrations/queries/rebuilds work?

> The data is there. If you create a new read model, it will build its state starting from the latest snapshot available, which aggregates the historic data, but there are some situations that are not easy to solve with the current version. For instance, right now it's hard to rebuild an entity state from scratch, for example, to start summing that interactionCount from the previous example. The easiest way to do that would be manually deleting all snapshots for an entity and submitting a new event, that would force the snapshots to be reprocessed and the read models to be overridden, but it's not an easy thing to do (yet) and manually handling this is quite error-prone.
Regarding schema migrations, we started an event migration mechanism that basically can upgrade an event from a previous version to a new version with a user-provided function. The idea is that entity snapshots and ReadModels are disposable, so being able to upgrade the events and deleting the previous snapshots is a relatively "easy" way to upgrade the overall schema. We have some doubts about this though, because this basically works as an event handler: events are tagged with a version number, and we have a transformation function from, let's say v1 to v2. It could be simpler to solve this with an actual event handler that listens to events of type ProductCreatedV1 and emits events of type ProductCreatedV2 without introducing extra DSLs. This is something that we should give a second thought yet.
Regarding queries, we're planning to offer a much richer GraphQL experience with more complex filters, and also let users do the same kind of queries from command or event handlers to make business logic decisions.
I don't know if I've been able to answer all your questions, but I would be happy to expand into any area, I know that someone in the team is currently working on a new section of the documentation with much deeper details on how the data is internally managed because it's definitely becoming a recurrent and important question to answer!

**Comment by NickSeagull** [comment]
Response by @alvaroloes 

> Regarding GraphQL count operations and paginations: Yeah we are working on it now. Currently, GraphQL "query" operations allow fetching read models using complex filters, but the syntax is not easy to use so that's why it is not documented and why we are working on a better one. As part of this work, we are adding support for pagination and other kind of queries

**Comment by NickSeagull** [comment]
Response by @javiertoledo 

> Exactly! One thing that makes a lot of sense is being able to project the data to different kinds of databases for different goals. DynamoDB is really good for key/value storage, but it makes some kind of queries very expensive. As all the data is generated from the event store, it's possible to project the read models to many different databases and keeping them all in sync. For instance, in addition to DynamoDB, you could want to project the data to a custom MySQL database where you can create indexes and perform more complicated queries or store the data with a different schema to optimize other workflow. We don't have a good native high-level API to use MySQL yet like the one we have for DynamoDB, but an event handler is just a node process, so nothing is stopping us from implementing a lower-level reducer that picks the current state from an entity in a MySQL table and updates the record with the data in the captured event. At the begining, we'll find some use cases where we'll need to go back to the lower level interfaces, but as we discover more and more interesting use cases, we can keep adding new abstractions to the Booster core that helps making things even easier. Integration mechanisms and data management are key topics where there's still a lot of room for improvement!

**Comment by jesusAlvSoto** [comment]
Closing this question as it has been answered and there has not been any follow-up for a long time.
