### ISSUE TITLE
Deleting items from tables

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#355]
Submitted by @tainguyenbui on Spectrum

> it might be a dumb question but I cannot find an example in the documentation. How do I delete a table item? For instance, I added a product but now I want to get rid of it.
There is an option, which is to add an isDeleted property to each Entity we create; however, that makes me a bit uncomfortable.
Would that create an overhead when retrieving, for instance, Get all available products? How would we specify such condition in the read model? For instance, in DynamoDB we could say something like: Scan all products which isDeleted property is true and it would return a list of items paginated. Also, would that be a problem when we face a huge table full of carts? The table would only grow, making it potentially full of cancelled carts, at the same time also more expensive to host and slower

**Comment by NickSeagull** [comment]
Yes, right now there is no way of deleting this on the read models. We will think about it in the future. Thanks!

**Comment by javiertoledo** [comment]
Closing, as it duplicates #1189
