### ISSUE TITLE
Weird behavior on register endpoint

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#357]
Submitted by @carlosper88 on Spectrum

> Today, when using the registration endpoint, I could register with Carlosperez@... Before that, I was also registered as carlosperez@... - note the capital 'C', so now I am registered twice. Maybe this is not a d desired behavior

**Comment by javiertoledo** [comment]
Closing this one, as this feature was moved to the auth rocket, which also has a pending refactor...
