### ISSUE TITLE
Read Sign up options from Booster Config when deploying Cognito user pool and deploy accordingly.

### ISSUE THREAD

**Issue by rdoria1** [boostercloud/booster#360]
Currently when deploying the Boost infra, Phone and email are always added as sign up options when deploying a new Cognito User Pool.
https://github.com/boostercloud/booster/blob/master/packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/auth-stack.ts#L49

Even if (unlikely) we all the roles defined in the Booster App only handle email or phone. 
We still still should read the Booster Config and check if among all declared roles, both sign up options are used and deploy accordingly.

For instance, let's say our `roles.ts ` file in our project looks like the following

```
import { Role } from '@boostercloud/framework-core'

@Role({
  auth: {
    // Do not specify (or use an empty array) if you don't want to allow sign-ups
    signUpMethods: [],
  }
})
export class Admin {}

@Role({
  auth: {
    signUpMethods: ['email'],
  }
})
export class User {}
```

Then we only need to specify email as sign up options when creating the Cognito User Pool.

**Comment by javiertoledo** [comment]
Related to the auth rocket
