### ISSUE TITLE
AWS::Lambda::Function pre-sign-up-validator Unzipped size must be smaller than 262144000 bytes

### ISSUE THREAD

**Issue by davidverdu** [boostercloud/booster#367]
While I'm deploying a Booster application this error is displayed and, consequently, a rollback occurs, preventing boost from creating all elements in AWS:

```text
26/57 | 11:12:17 | CREATE_FAILED        | AWS::Lambda::Function                  | pre-sign-up-validator (presignupvalidator8052074C) Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2798c5eb-e996-4112-a8a8-439fa4f6636d)
	new Function (/booster_project/node_modules/@aws-cdk/aws-lambda/lib/function.ts:460:35)
	\_ AuthStack.buildUserPool (/booster_project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/stacks/auth-stack.js:26:33)
	\_ AuthStack.build (/booster_project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/stacks/auth-stack.js:19:35)
	\_ ApplicationStackBuilder.buildOn (/booster_project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/stacks/application-stack.js:27:62)
	\_ assemble (/booster_project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:46:61)
	\_ Object.synthesizer (/booster_project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:72:44)
	\_ AppStacks.synthesizeStacks (/booster_project/node_modules/aws-cdk/lib/api/cxapp/stacks.ts:205:41)
	\_ AppStacks.listStacks (/booster_project/node_modules/aws-cdk/lib/api/cxapp/stacks.ts:179:33)
	\_ deployApp (/booster_project/node_modules/@boostercloud/framework-provider-aws-infrastructure/dist/infrastructure/index.js:59:38)
	\_ processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I'm using MacOS and Booster 0.5.1. Here I attach my package.json:

```json
{
  "name": "booster_project",
  "description": "",
  "version": "0.1.0",
  "author": "",
  "dependencies": {
    "@boostercloud/framework-core": "^0.5.1",
    "@boostercloud/framework-types": "^0.5.1",
    "@boostercloud/framework-provider-aws": "*",
    "@types/dotenv": "^8.2.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link-http": "^1.5.17",
    "aws-sdk": "^2.695.0",
    "cross-fetch": "^3.0.4",
    "dotenv": "^8.2.0",
    "firebase-admin": "^8.12.1",
    "graphql-tag": "^2.10.3"
  },
  "devDependencies": {
    "@boostercloud/cli": "^0.5.1",
    "@boostercloud/framework-provider-aws-infrastructure": "*",
    "@types/faker": "^4.1.12",
    "@types/node": "^13.5.1",
    "@typescript-eslint/eslint-plugin": "^2.18.0",
    "@typescript-eslint/parser": "^2.18.0",
    "chai": "^4.2.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "faker": "^4.1.0",
    "mocha": "^7.0.1",
    "nyc": "^15.0.0",
    "prettier": "^1.19.1",
    "rimraf": "^3.0.1",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5",
    "@types/chai": "^4.2.7",
    "@types/chai-as-promised": "^7.1.2",
    "@types/mocha": "^7.0.2"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "homepage": "",
  "license": "MIT",
  "main": "dist/index.js",
  "repository": "",
  "scripts": {
    "lint:check": "eslint --ext '.js,.ts' **/*.ts",
    "lint:fix": "eslint --quiet --fix --ext '.js,.ts' **/*.ts",
    "compile": "tsc -b tsconfig.json",
    "deploy": "boost deploy",
    "clean": "rimraf ./dist tsconfig.tsbuildinfo",
    "test:unit": "",
    "test:integration": "AWS_SDK_LOAD_CONFIG=true nyc --extension .ts mocha --forbid-only \"tests/**/*.test.ts\"  --config \"tests/integration/.mocharc.yml\""
  },
  "types": "lib/index.d.ts"
}
```

I believe that the package aws-sdk is causing the problem.

**Comment by NickSeagull** [comment]
Thanks for pointing out, this means that your app is huge in size and AWS Lambda. In the case of AWS, the `aws-sdk` library is already pre-loaded in the lambdas, so you can safely move it to the `devDependencies` section.

We should document this special case

**Comment by alvaroloes** [comment]
Another point is that, right now, when you deploy the application using `boost deploy`, Booster is taking your entire project root and zipping it. This is OK, but it is likely that it includes a lot of `devDependencies` that are not used by the deployed code. Booster should first install all dependencies in "production mode" before zipping and deploying. This work will be done in #374

**Comment by AdrianLorenzoDev** [comment]
Hello!

We are **in the need of using the `firebase-admin` package** to send notifications using `FCM` using event handlers, so **it needs to be a production dependency**, but **we reach the 250MB AWS Lambda limit** if we use it.

Currently, how difficult would it to create a functionality in Booster **to include dependencies as a set of [AWS Lambda Layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html) on deployment**? I think it could be a great solution to this problem.

**Comment by rdiaz82** [comment]
According to the documentation lambdas can have a maximim of 5 layers but the size couldn't exceed the 250MB.

I would bet to create the production build during the deploy to solve this. The production build will reduce the size more than 50% for sure.

**Comment by vukgogo** [comment]
Hey all, I'm just trying to see what I'm doing wrong on my end. So I tried the basic sample Blog Post (in the Booster Intro Documentation).

Here are my dependencies:

```
"dependencies": {
    "@boostercloud/framework-core": "^0.9.1",
    "@boostercloud/framework-provider-aws": "*",
    "@boostercloud/framework-types": "^0.9.1"
  },
  "devDependencies": {
    "@boostercloud/cli": "^0.9.1",
    "@boostercloud/framework-provider-aws-infrastructure": "*",
    "@types/node": "^13.5.1",
    "@typescript-eslint/eslint-plugin": "^2.18.0",
    "@typescript-eslint/parser": "^2.18.0",
    "aws-sdk": "^2.793.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "mocha": "^7.0.1",
    "nyc": "^15.0.0",
    "prettier": "^1.19.1",
    "rimraf": "^3.0.1",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5"
  }
```
And running the command: 

`boost deploy -e production`

Throws the error described in this Issue:

```
CREATE_FAILED  | AWS::Lambda::Function  | graphqlhandler
Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;
```

Some extra details:

Node: 12.19.0 
NPM: 7.0.3
Booster: @boostercloud/cli/0.9.1
OS: MacOS Mojave 10.14.6

**Comment by javiertoledo** [comment]
@davidverdu @AdrianLorenzoDev @vukgogo There's a bug that is including all devDependencies in the deployed zip. While we work on a fix, one workaround that you could try is to remove the `@boostercloud/framework-provider-aws-infrastructure` from your devDependencies and install it globally. This package is dynamically required by the CLI when you run the deploy or nuke command, but your project doesn't actually need it. You can do this by running these commands in your project root:

    npm uninstall @boostercloud/framework-provider-aws-infrastructure
    npm install -g @boostercloud/framework-provider-aws-infrastructure

**Comment by carlosper88** [comment]
@javiertoledo I've been also facing this same issue, but I don't get to solve it with the commands you wrote (I even tried nuking the project and deploying back again). I keep having that same error:

```
10:17:19 | CREATE_FAILED        | AWS::Lambda::Function                  | presignupvalidator8052074C
Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 9190041f-2092-44ba-8766-
0b561e6a558f; Proxy: null)
```

Booster version: @boostercloud/cli/0.9.1 darwin-x64 node-v14.2.0
NPM version: 6.14.5
Node version: v14.2.0

Is there any other workaround I can do? Thanks in advance

**Comment by javiertoledo** [comment]
Try to remove all devDependencies from the project before deploying it:

    $ npm install --production --no-bin-links

and then...

    $ boost deploy

🤞🤞🤞

**Comment by carlosper88** [comment]
That returns an error saying 

`Error: Cannot find module '@boostercloud/framework-provider-aws-infrastructure'
`

In my case, the ones I removed from devDependencies were

```
    "@boostercloud/framework-provider-local": "^0.9.1",
    "@boostercloud/framework-provider-local-infrastructure": "^0.9.1",
    "@boostercloud/framework-provider-aws-infrastructure": "^0.9.1",
```

so it makes sense not to find that module

**Comment by javiertoledo** [comment]
Even if it's installed globally?🤔

Well, we'll investigate and try to come up with a more permanent solution...

**Comment by carlosper88** [comment]
We finally got it. Thanks to @AdrianLorenzoDev 
Before getting to the solution, we tried using @javiertoledo approach of:
`$ npm install --production --no-bin-links`
and
`npm install @boostercloud/framework-provider-aws-infrastructure --save-dev`
with no luck.

What we finally did was to:
- Remove node_modules
- Remove package-lock.json
- Use yarn

There was no need to remove the dependencies from package.json. It worked like a charm and we are now able to deploy as normal

**Comment by javiertoledo** [comment]
Interesting... how exactly did you use yarn? Was `yarn install` just enough? Did it actually reduce the size of the deployed zip? We should make sure that we understand why this worked...

**Comment by javiertoledo** [comment]
I'm still working on a more permanent solution in #499. Given that we use yarn in the whole project and it seems to be producing more predictable outcomes right now, I'm updating the docs to recommend using `yarn` instead of `npm` in user projects too. I noticed that we've been using `yarn` in our integration tests, so this could be the reason why this issue went unnoticed until now.

While I work in this PR, you can try what @carlosper88 suggested, but also installing the dependencies in production mode. The full sequence of commands would be:

    # First make sure you don't keep what npm installed
    rm -rf node_modules
    rm -f package-lock.json

    # Install the dependencies with yarn, this will generate a yarn.lock file
    yarn install

    # To deploy your project, make sure you install the dependencies in production mode, and then run the deployment normally
    yarn install --production --no-bin-links
    boost deploy -e production

    # Remember to reinstall the dev dependencies after the deployment to keep working locally
    yarn install

Once #499 is merged, the steps required to install the dependencies in production mode will be handled by the booster cli
