### ISSUE TITLE
Booster should deploy the application including only the "production" dependencies

### ISSUE THREAD

**Issue by alvaroloes** [boostercloud/booster#374]
### Description
When deploying a Booser application, we are taking the whole project root, zipping it, and uploading it to the provider. This is OK, but we are including a lot of dependencies only meant for the development phase (those inside `devDependencies` in the package.json file), like the typescript compiler, and they can weight a lot. 

This is causing problems like the one reported here #367 .

This can be fixed by reinstalling the dependencies in production mode, similar to what we are doing when deploying the integration tests application using a custom script ([here](https://github.com/boostercloud/booster/blob/2184810c17b5cba447839e4763f0018900bde447/packages/framework-integration-tests/src/deploy.ts#L57))

### Acceptance criteria
- The code deployed to the provider should include only the dependencies needed for runtime (production) and not those needed for development time.
- After deployment, the project root should be left as it was before the deployment. This means that the developer should still find the development dependencies installed and usable

**Comment by davidverdu** [comment]
@alvaroloes is this issue solved in your recent PR where you install the dependencies in the .deploy sandbox folder? Or this issue is another problem we need to solve?

**Comment by alvaroloes** [comment]
Yes!!! Thanks for catching this. Closing!

**Comment by alvaroloes** [comment]
Solved in version 0.10.0
