### ISSUE TITLE
AWS - Custom userpool user configuration

### ISSUE THREAD

**Issue by MYF95** [boostercloud/booster#381]
Would it be possible to somehow add "custom" configuration regarding how to manage the user pools in AWS? 

It seems by default the current way to verify users is by email.
Given cognito doesn't really seem to offer any options regarding URL callbacks to redirect to the page we want, as well as the page of cognito being pretty basic and not representing the brand (you could do it by adding css through the cognito console... but it sounds really cumbersome).

It also seems the `userAttribute: { role: string }` is not really creating a new Group in cognito to have separate roles per se. Is it only a denomination to be used inside booster?

**Comment by javiertoledo** [comment]
Hi @MYF95, current auth implementation is very basic and can't be easily extended/configured. We're currently working on a re-architecture to extract auth from the Booster core into its own package. That should allow you to use Cognito APIs directly, choose other solutions like Auth0 or roll out your own auth solution if you want to.

**Comment by javiertoledo** [comment]
Auth was removed from the Booster core
