### ISSUE TITLE
Enable CORS in the auth endpoints

### ISSUE THREAD

**Issue by itrion** [boostercloud/booster#387]
There is a CORS issue in the AWS provider because the `auth` resource within the `httpUrl` API Gateway does not support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), and it is making the Booster generated applications unusable from web clients, see #311 

![image](https://user-images.githubusercontent.com/3480612/91196276-d697c980-e6f1-11ea-8ab8-5f386e2d01c5.png)

**Acceptance criteria**
The generated `auth` resource must:
- Support the [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) by adding an `OPTIONS` method returning these headers, e.g.

```http
OPTIONS /auth/sign-up

Access-Control-Request-Method: OPTIONS,POST
Access-Control-Request-Headers: *
Origin: *
```
- Include one `POST` methods under each `/auth/sign-up`, `/auth/sign-in` and `/auth/sign-out` resources with the `Access-Control-Allow-Origin: * ` header in the response.

Regarding the headers' values, we can default `Access-Control-Request-Method` to `OPTIONS,POST` because we are not generating more methods than those. And we can default `Access-Control-Request-Headers` to `Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token` because that's what AWS suggests.

**We still might need to answer:**
- What should be the value for the `Origin` header in the preflight request?
- What should be the value for the `Access-Control-Allow-Origin` header in the POST requests?

As a first iteration, and to avoid making the issue's scope too big, we can default them to `*`, but ideally, the user must be able to configure the allowed domains for CORS.

What do you think @javiertoledo @NickSeagull @alvaroloes ?

**Comment by javiertoledo** [comment]
Right now we should make these headers `*` to fix the issue. We could consider adding extra configuration options, but I'd wait to see someone actually requesting that feature before implementing it.
