### ISSUE TITLE
Fetch Read Model from Command or filter Entity snapshot

### ISSUE THREAD

**Issue by carlosper88** [boostercloud/booster#389]
I've been trying to create a side project with Booster, but there's a point where I get stuck. In one of the commands I need to fetch some data from the database. For fetching this data, some filtering is needed, so the `fetchEntitySnapshot` doesn't work for me as it requires an id to be passed as an argument.

My second thought was to try to read a readModel from inside the command, but I'm not sure this is possible with current Booster implementation. Is there any way to achieve this?

The last workaround would be to somehow create a readModel with the data already filtered and let the client read it and then pass it through the command where the filter is needed, but this would involve some extra work and complexity on the client-side.

As you can see, `fetchEntitySnapshot` with some filtering or commands being able to read readModels, would be the best approaches here. Is it possible or is it planned to be possible to do this with Booster anywhere soon?

**Comment by NickSeagull** [comment]
Hey, thanks for pointing this out!

Booster doesn't support filtering entities, nor fetching read models right now. I'm gonna edit the issue so it is more a feature request, which is easier for us core devs to filter when looking at the open issues :)

**Comment by javiertoledo** [comment]
We have been discussing a little bit about this and agree that being able to query read models would be a nice addition to the framework. One workaround to achieve this without waiting for us to implement this feature would be to directly use the [DynamoDB SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html) from your command handler and [do a scan](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#scan-property) yourself on the corresponding read model table. You should be able to build the read model table name dynamically with the info in the `Booster` object doing something like this (you might need to cast it to `any` to access the private fields of that object in runtime  :trollface:):

```typescript
const boosterHacked = Booster as any
const tableName = boosterHacked.config.resourceNames.forReadModel(readModelName)
```

The only thing that you must take into account is when reading read models is that they are eventually consistent caches of the data in the entities, so the data might not be 100% up to date at the moment of reading them.

**Comment by carlosper88** [comment]
Thanks, Javi, I'll take a look. For my functionality, I think I'll have pretty static data, so it shouldn't be a problem if they're not 100% up to date, as they won't be changing over time.

**Comment by juanjoman** [comment]
We can already do `Booster.readModels` with filters, is there anything else we should address about this issue? @carlosper88

**Comment by carlosper88** [comment]
@juanjoman I think we can close this, as the `Booster.readModel` feature allows us to fetch readModel from command and another readModel
