### ISSUE TITLE
Think on ways to automate release notes

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#421]
We're currently editing release notes manually every time a version is released. It could be handy that release notes are gathered from comments that the developers leave in their own commits, merge commits, or some shared file that is reset when a new version is released. Other ideas are more than welcome!

**Comment by NickSeagull** [comment]
Definitely, the key would be to force conventional commits, something like in [this post](https://medium.com/@imdavidrock/why-should-you-use-commitizen-husky-for-conventional-commit-and-have-unified-lint-41047aad6d)
