### ISSUE TITLE
Can't query read-model with primitives array (string) property

### ISSUE THREAD

**Issue by adrian-lorenzo** [boostercloud/booster#436]
**Booster version:** `0.7.1`
**Provider:** `AWS`

# Description

I have a Booster application with **a read-model which has a `Array<string>` property**. When the entity related to it gets reduced, **everything works fine and no errors are shown in the `CloudWatch` log**, and the data in `DynamoDB` is correct. 

However, **when querying the read model using the GraphQL API, I receive an error indicating that it could not parse the value because it is not an object.** I tried by using the `String` object instead of the primitive type without success. 

I think it might be related to the `graphql-type-json` package, which [seems to be](https://github.com/taion/graphql-type-json/blob/master/src/index.js) the one throwing the error.

```
{
    "errors": [
        {
            "message": "JSONObject cannot represent non-object value: this_is_a_value",
            "locations": [
                {
                    "line": 8,
                    "column": 9
                }
            ],
            "path": [
                "ReadModel",
                "query",
                0
            ]
        }
    ],
    "data": {
        "ReadModel": {
            "id": "x",
            "arrayOfStrings": [
                null
            ]
        }
    }
}
```

**Comment by NickSeagull** [comment]
Yep, right now this is an issue, one work around is to wrap this array in an object like:

```ts
// instead of returning
        {
            "id": "x",
            "arrayOfStrings": [
                null
            ]
        }

// return
        {
            "id": "x",
            "arrayOfStrings": { value: [ null ] }
        }
```

Ugly, but it works
