### ISSUE TITLE
Install dependencies in production mode before deploying

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#441]
Right now we are just deploying the app as it is, but `npm` supports installing the deps in production mode, which halves the size of the zip at least by half.

**Comment by sanskar-p** [comment]
Hi @NickSeagull, I'd like to work on this but I'm not sure exactly what to do. I would appreciate your advice on this. Thanks!

**Comment by NickSeagull** [comment]
Hey @sanskar-p , thanks for the ping! 

What's happening currently is, that before deploying the project, we are uploading the whole root project. Which is not **that** bad, except that it also brings with it the entire `node_modules` folder, ending up with a huge folder, with all the `devDependencies` and their transitive dependencies.

The idea here would be to add an additional step in [this file](https://github.com/boostercloud/booster/blob/master/packages/cli/src/commands/deploy.ts), doing something like

```ts
.step('Prunning dependencies', pruneDependencies)
```

And write an appropriate `pruneDependencies` function that executes `npm prune --production` in the root of the user's project.

Feel free to reach me if you need more help with this :)

**Comment by sanskar-p** [comment]
@NickSeagull, so for the `pruneDependencies` function, I'm thinking of creating a shell script in `booster/scripts/` with the following contents:
```
cd ..    #to go to root
npm prune --production
```

And we can call this function in a step before line 19 in [this](https://github.com/boostercloud/booster/blob/master/packages/cli/src/commands/deploy.ts#L19) file.

What do you think about this?

**Comment by Fecony** [comment]
@sanskar-p scripts folder in project root is used to run lerna scripts and other things to build, publish or test package.

Take look at https://github.com/boostercloud/booster/blob/master/packages/cli/src/commands/new/project.ts#L76
there are installed dependencies when new project is created.

**Comment by NickSeagull** [comment]
Yes, what @Fecony said it is right. The scripts folder doesn't exist when the user installs the CLI tool, it has to be inside of the command like @Fecony pointed

**Comment by sanskar-p** [comment]
@NickSeagull, @Fecony,
So referring to the [`installDependencies`](https://github.com/boostercloud/booster/blob/fb14668e36c53fd883d764cb60ea9088cab36fbf/packages/cli/src/services/project-initializer.ts#L20) function, I've written the following:

```
async function pruneDependencies() {
  try {
    await exec('npm prune --production', {})
  } catch (e) {
      throw wrapExecError(e, 'Could not prune dev dependencies')
  }
}
```
I'm not sure what to put as the 2nd parameter in the `exec` line to refer to the root directory. 
Sorry if I'm doing this wrong :sweat_smile:

**Comment by NickSeagull** [comment]
Hey @sanskar-p , you can have the `pruneDependencies` function receive a parameter `config: ProjectInitializerConfig`, as the `step` function will pass it to it. Then you can do the same thing as in `installDependencies`

**Comment by sanskar-p** [comment]
> Hey @sanskar-p , you can have the `pruneDependencies` function receive a parameter `config: ProjectInitializerConfig`, as the `step` function will pass it to it. Then you can do the same thing as in `installDependencies`

I did what you said but I'm getting the following error message: `Argument of type '(config: ProjectInitializerConfig) => Promise<void>' is not assignable to parameter of type '(ctx: BoosterConfig) => Promise<void>'.
  Types of parameters 'config' and 'ctx' are incompatible.
    Type 'BoosterConfig' is missing the following properties from type 'ProjectInitializerConfig': projectName, description, version, author, and 6 more.ts(2345)`

when I write this: (corresponding to [this function](https://github.com/boostercloud/booster/blob/fb14668e36c53fd883d764cb60ea9088cab36fbf/packages/cli/src/services/project-initializer.ts#L64))
```
function projectDir(config: ProjectInitializerConfig): string {
  return path.join(process.cwd(), 'config.projectName')
}
```
Instead, can I just explicitly define the projectName as `booster`?
```
function projectDir(): string {
  return path.join(process.cwd(), 'booster')
}
```

**Comment by NickSeagull** [comment]
@sanskar-p then I'd change the type of `config` to `BoosterConfig`.

The project dir would `process.cwd()` because its where the user will use the tool.
We cannot assume that the name will be `booster` because we don't know the project name of the user in that point, but we can assume that it will be executed from the root of the project

**Comment by sanskar-p** [comment]
Okay I have made the modifications @NickSeagull 
Here is the `pruneDependencies` function:
```
async function pruneDependencies(config: BoosterConfig): Promise<void> {
  try {
    await exec('npm prune --production', { cwd: projectDir(config) })
  } catch (e) {
    throw wrapExecError(e, 'Could not prune dev dependencies')
  }
}
```
And here is the `projectDir` function:
```
function projectDir(config: BoosterConfig): string {
  return path.join(process.cwd());
}
```

Should I send a PR with the above changes?

**Comment by NickSeagull** [comment]
Yes, please, remember to test your changes and write some unit tests please :)
