### ISSUE TITLE
Perform a `git init` after creating a new project

### ISSUE THREAD

**Issue by Fecony** [boostercloud/booster#445]
It'd be great if we could initialize git with default commit message like `Initial commit`.
And create `--no-git` cli flag to skip this step.

**Comment by Fecony** [comment]
@NickSeagull I started to work on this issue, can you assign me? 👀

**Comment by NickSeagull** [comment]
Done @Fecony

**Comment by Fecony** [comment]
Solved in https://github.com/boostercloud/booster/pull/456
