### ISSUE TITLE
Integration test for CLI don't work

### ISSUE THREAD

**Issue by VeroGarp** [boostercloud/booster#449]
## Current Behavior

Integration test don't pass on master

## Expected behavior

Integration test pass

## Possible Solution

No idea

## Additional information

See the attached file
[integration_test_error.txt](https://github.com/boostercloud/booster/files/5366815/integration_test_error.txt)

#### Environment

- Booster version: master
- Node/npm version: v14.13.1/6.14.8
- OS: Windows 10

**Comment by javiertoledo** [comment]
Will be fixed in #476
