### ISSUE TITLE
CLI integration tests delete files from the repo

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#460]
## Current Behavior

After running `lerna run integration/cli` the file `packages/framework-integration-tests/src/read-models/cart-read-model.ts` is deleted, resulting in changes in the repo that might be accidentally pushed.

## Expected behavior

After running integration tests, the repo stays the same.

## Possible Solution

Remove the code from the integration tests that deletes this file

**Comment by javiertoledo** [comment]
This will be solved once #414 is merged
