### ISSUE TITLE
Add Press Kit about booster logo/font usage

### ISSUE THREAD

**Issue by Fecony** [boostercloud/booster#466]
## Documentation bug, improvement

Not really documentation I think?

## Description

It would be nice to add Press kit for booster visual guide. For example when people will write blog posts, guides, tutorials or news about booster framework they can use this page/section as guide on "how-to" properly use logo, logo / font sizes, color, fonts, name.  

**Example:**

- https://angular.io/presskit
- https://getstencil.com/press
- https://en.facebookbrand.com/

**Comment by javiertoledo** [comment]
That's a fantastic idea, I think that we have most of that ready, but we haven't published it yet. I'll ask our designers!

**Comment by LaiaPerez88** [comment]
Hey @Fecony! We have included the Booster press kit on [our website](https://www.booster.cloud/). You can find it at the end of the landing.

![image](https://user-images.githubusercontent.com/10027992/97881231-0b3f8700-1d1a-11eb-865f-121a17a22401.png)
