### ISSUE TITLE
Subscription does not send data updates due to a high payload size

### ISSUE THREAD

**Issue by AdrianLorenzoDev** [boostercloud/booster#472]
## Current Behavior

In my Booster project, I have a read-model which stores a list of objects. **When submitting a subscription request to the server for a certain instance this read-model using a client, even if a read-model update is being generated, the subscription does not send any update message.** 

After taking a look to the `CloudWatch` logs, it seems like the read-model subscription is not sending the last version available **because the message to be sent has exceeded its maximum size**:

![image](https://user-images.githubusercontent.com/24827940/96875002-a610a980-146e-11eb-8096-22ec1a767199.png)

I tried to do the same **test with a read-model instance that does not have too many items in the list, and the subscription is working properly with it.**

## Expected behavior

The read-model subscription delivering the last version of the data.

#### Environment

- Booster version: `0.8.2`
- Node/npm version: `14.8.0`/`6.14.17`
- OS: MacOS `10.15.6`

**Comment by AdrianLorenzoDev** [comment]
After testing and looking for solutions to this problem, my teammates realised that it is not a problem of the framework itself, but just a design limitation of the websocket.

I decided to refactor my project read-models to avoid reaching the limited websocket message payload size. However, I noticed that the user that reached the limit before is not receiving subscription updates properly since that situation. Sometimes it receives the value, but not frequently. With another user, everything works flawlessly. Do you think that it is maybe related to some kind of cache from Apollo or Booster?

**Comment by javiertoledo** [comment]
I'm feeling curious about the size of that message now, but I guess this means that we can close this ticket..
