### ISSUE TITLE
new:project fails if quotes ocurr in any of the fields

### ISSUE THREAD

**Issue by NickSeagull** [boostercloud/booster#492]
## Current Behavior

The quotes aren't being escaped, resulting in a malformed `package.json` file

## Expected behavior

Quotes are escaped

## Possible Solution

Perform a replace of the `'` and `"` characters with `\'` and `\".

#### Environment

- Booster version: 0.9.0

**Comment by davidverdu** [comment]
Replacing ' was not necessary. Replacing " with \" fixes the bug
