### ISSUE TITLE
Remove real file operations from cli unit tests

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#503]
There are real file interactions in CLI unit tests for `boost new:project ...` ([packages/cli/test/commands/new.test.ts](https://github.com/boostercloud/booster/blob/master/packages/cli/test/commands/new.test.ts#L8)).

Unit tests should not perform real operations of any kind, all side effects must be stubbed. We have integration tests to check that.

We should replace these tests with ones that stub the file operations.

**Comment by davidverdu** [comment]
I have created a PR for this issue: https://github.com/boostercloud/booster/pull/525
