### ISSUE TITLE
Missing rimraf dependency in cli package

### ISSUE THREAD

**Issue by adriangmweb** [boostercloud/booster#509]
# Bug Report

## Current Behavior

When trying to use the latest `cli` package `v0.9.3` globally, the `rimraf` dependency is missing.

## Expected behavior

When using the `cli` globally installed it should execute the commands without throwing a missing dependency error. e.g., `boost deploy -e production`

## Possible Solution

Add `rimraf` into the `cli` package dependencies.

### Environment

- Booster version: `0.9.3`
- Node/npm version: 12.20.0
- OS: OSX 11.1 Big Sur

**Comment by davidverdu** [comment]
@alvaroloes I assign you the issue since it's about to be solved with your PR https://github.com/boostercloud/booster/pull/576

**Comment by alvaroloes** [comment]
Yep thanks!

**Comment by alvaroloes** [comment]
This is now fixed in version 0.11.2. Please check release notes: https://github.com/boostercloud/booster/releases/tag/v0.11.2
