### ISSUE TITLE
Unable to get the GraphQL API schema

### ISSUE THREAD

**Issue by rdiaz82** [boostercloud/booster#523]
# Bug Report

## Current Behavior

GraphQL schema is not working. In any graphQL client if you try to get the schema you get an error 405 (method not allowed). In spite of this error, the GRaphQL API is working because I have checked and I was able to perform a mutation and a query without any problems.

## Expected behavior

The expected behavior is to get the graphQL API schema.

## Possible Solution

Checking in the API gateway I have seen that the API only has enabled the POST method, So I guess that the problem could be there. During the deployment, the cloud formation template probably is not setting the API gateway for GET operations. 
![Screenshot 2020-12-21 at 23 50 35](https://user-images.githubusercontent.com/5313797/102832912-a0403180-43e7-11eb-919e-318199993bb7.png)
### Environment

- Booster version: 0.9.1
- Node/npm version: node 12.16.1 / npm 6.13.4
- OS: OSX 10.15.3

**Comment by javiertoledo** [comment]
@alvaroloes what do you think about it? This is either a bug or we need to clarify this in the documentation...

**Comment by rdiaz82** [comment]
I would say that this was working in the past, I wouldn't put my hand over the fire but I have seen schemas in Postwoman.

The only thing that I doubt is If I saw that schema using the kubernetes provider  or using the aws provider.

**Comment by NickSeagull** [comment]
Yes, this was working with AWS, in fact I was using it last month 😱

**Comment by rdiaz82** [comment]
could happen that it is fixed because @davidverdu I think that has been able to get it. @davidverdu could you confirm that this is working?

**Comment by davidverdu** [comment]
@rdiaz82 I haven't touched anything related to GraphQL. Nonetheless, I'm about to refactor the GraphQLGenerator class as is proposed in this issue (https://github.com/boostercloud/booster/issues/541). If there is an error maybe I can try to solve it, but I need more context to do that.

**Comment by javiertoledo** [comment]
AFAIK when you connect to your API using Postwoman or other GraphQL client, you can see the schema. Are we sure that we want to be able to get the schema using an actual `GET` operation? I'm not sure this is standard TBH

**Comment by NickSeagull** [comment]
Schemas are retrieved by `POST` ing the `IntrospectQuery` GraphQL query, which is a special GraphQL query that returns the schema, I don't think it should be `GET`ted

**Comment by davidverdu** [comment]
Definitely it works with `POST`. I've found that the bug occurs when no readModel is defined in your project. I'm working on the FIX
