### ISSUE TITLE
Unexpected requirements on new deployment (0.10.0)

### ISSUE THREAD

**Issue by AdrianLorenzoDev** [boostercloud/booster#580]
# Bug Report

## Current Behavior

With the new improved deployment process, I am getting new errors due to the following requirements:

- Missing file `.eslintignore`

```
 Error: ENOENT: no such file or directory, copyfile '.eslintignore' -> '.deploy/.eslintignore'
    Code: ENOENT
```

- Missing file `tsconfig.eslint.json`

```
Error: ENOENT: no such file or directory, copyfile 'tsconfig.eslint.json' -> '.deploy/tsconfig.eslint.json'
    Code: ENOENT
```

- Missing package `rimraf` (global install).

```
rimraf ./dist tsconfig.tsbuildinfo

sh: rimraf: command not found
npm ERR! code ELIFECYCLE
```

- `index.js` path is wrong.

```
 Error: Error: Cannot find module '/MyWonderfulBoosterProject/dist/index.js'
```

## Expected behavior

I expected a deployment without this new undocumented requirements.

## Possible Solution

* Optional copy of `.eslintignore` and `tsconfig.eslint.json` (only if exists).
* Add `rimraf` as a dependency of Booster and change call to local (without path inference).
* Change userApp directory:

Before:

``` typescript
const userApp = require(path.join(process.cwd(), 'dist', 'index.js'));
```

After:

``` typescript
const userApp = require(path.join(process.cwd(), '.deploy/dist', 'index.js'));
```

### Environment

- Booster version: [e.g. 0.8.2]  `0.10.0`
- Node/npm version: [e.g. Node 8/npm 5]  `node 14.8.0`/`npm 6.14.7`
- OS: [e.g. OSX 10.13.4, Windows 10] `MacOS Big Sur 11.1`

**Comment by alvaroloes** [comment]
Do you get these errors when you execute `boost deploy`?

**Comment by AdrianLorenzoDev** [comment]
I use `boost deploy`, @alvaroloes, but not the global version. I use a local dev version of the package:

`./node_modules/@boostercloud/cli/bin/run deploy -e development`

**Comment by Kalm004** [comment]
Just for adding more details, just following "Your first Booster app in 10 minutes" I also experienced the "Missing package rimraf" with a fresh node 14 installed.

**Comment by AdrianLorenzoDev** [comment]
@Kalm004 we have found a solution to this problem. It is related to the `package.json` scripts.

Right now, you should have the following scripts in your project `package.json`:

```text
scripts: {
    "lint:check": "eslint --ext '.js,.ts' **/*.ts",
    "lint:fix": "eslint --quiet --fix --ext '.js,.ts' **/*.ts",
    "compile": "tsc -b tsconfig.json",
    "deploy": "boost deploy",
    "clean": "rimraf ./dist tsconfig.tsbuildinfo", // This is the one that is giving you problems
}
```

Booster installs `rimraf` as a development dependency, and the problem is that the `.deploy` target is not locating the package in the parent directory. The solution is to force the usage of the local environment when executing the scripts, which can be done using `npx`:

```text
scripts: {
    "lint:check": "npx eslint --ext '.js,.ts' **/*.ts",
    "lint:fix": "npx eslint --quiet --fix --ext '.js,.ts' **/*.ts",
    "compile": "npx tsc -b tsconfig.json",
    "deploy": "boost deploy", // boost is a global dependency. We don't use npx here.
    "clean": "npx rimraf ./dist tsconfig.tsbuildinfo",
}
```

This should solve the problem 😄
