### ISSUE TITLE
Deploy not working due to compilation error

### ISSUE THREAD

**Issue by Kalm004** [boostercloud/booster#592]
# Bug Report

After following the "Your first Booster app in 10 minutes" guide in the documentation, when I tried to execute "boost deploy" I saw the following problem.

![image](https://user-images.githubusercontent.com/6499143/106391088-782eef80-63e3-11eb-9aa6-440806ddea0d.png)

I found a workaround for this to work by adding:
"compilerOptions":
        "skipLibCheck": true

To the tsconfig.json file. But I'm sure that this is not the correct solution for this problem.

### Environment

- Booster version: @boostercloud/cli/0.11.1 darwin-x64 node-v14.15.4
- Node/npm version: node-v14.15.4 / npm 6.14.10
- OS: OSX 10.15.7

**Comment by alvaroloes** [comment]
This is the first time I see it 😳
