### ISSUE TITLE
PascalCased resource class name

### ISSUE THREAD

**Issue by Fecony** [boostercloud/booster#620]
## Feature Request
Adjust resource generation

## Description
When trying Booster cli, I have noticed that it doesn't change provided name for resource. 
For example, if I run `boost new:command testCommand` it will generate `test-command.ts` file with `testCommand` class name. Then, eslint will point out, that `Class 'testCommand' must be PascalCased.eslint@typescript-eslint/class-name-casing`

![image](https://user-images.githubusercontent.com/36774784/108562120-0e31a800-7308-11eb-9515-78d823fb6e5e.png)

**Comment by NickSeagull** [comment]
Thanks for reporting! Indeed, the Booster CLI should enforce Pascal casing

**Comment by Fecony** [comment]
Closed in #660, #799 ✅
