### ISSUE TITLE
Fix project template tests

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#63]
**Description**
**Given** I am a user that has created a Booster project

**When** I run tests

**Then** I should be returned my test results

**Current behavior:**

Tests are missing some key `dev dependencies`

- `mocha`
- `ts-node`

**Steps to reproduce:**

1. Create a booster project from template
2. run `npm run test`

**Steps to fix:**

1. add `mocha` dev dependency
2. add `ts-node` dev dependency
3. run `npm run test`

**Notes:**

It is possible that this does not occur of you have `mocha` and `ts-node` installed as global dependencies

**Comment by glammers1** [comment]
Hi, @NickSeagull I've been taking a look at this issue and I think it's already done. Those dependencies are already in the [template](https://github.com/boostercloud/booster/blob/master/packages/cli/src/templates/project/package-json.ts#L18). I was able to create and run some tests in a Booster project (without having mocha installed globally). Am I missing something?

**Comment by NickSeagull** [comment]
Perhaps this is an outdated one, feel free to reopen if it appears again
