### ISSUE TITLE
Consider using Docusaurus to organize documentation better

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#638]
Creating this from [a comment by @Fecony](https://discord.com/channels/763753198388510780/781960568541806593/813729050358972428)

Recently I found https://v2.docusaurus.io/ (ugh I knew about it, just found it again xd)
It has versioning what I consider NICE feature for docs, since booster versions change some stuff and it could be better if It was documented as well

Like Laravel versions have examples in each version even when they change methods

I don't know what you think about making docs, But I though about structure like:

- Installation
- Booster introduction
- About Resources and what they do
- In-depth about something (resources)
- Into about events and how it works (differences from mvc people are used to and etc)
- How GraphQL works
- Rockets (static site, etc)
- Examples?
- Tooling
- Contribution (How, where)
- Useful resources (when there will be tutorials and rockets) (Booster awesome like Vue awesome with resources xd)
- Other info (about THEAM for example)

Because even after reading docs I have a lot of questions. I think it is expected, since those events are new to me, but idk :smile:

**Comment by jesusAlvSoto** [comment]
This was done in https://github.com/boostercloud/booster/pull/1253
