### ISSUE TITLE
Compilation error when using filter on Search<ReadModel>

### ISSUE THREAD

**Issue by AdrianLorenzoDev** [boostercloud/booster#639]
# Bug Report

## Current Behavior

On compilation phase (`tsc -b tsconfig.json`), **I'm getting this error in an application which is currently deployed with the same dependencies version and even the same `node_modules` files**. I just re-deployed the application.

```
src/scheduled-commands/DeletionScheduledJob.ts(15,30): error TS2554: Expected 1 arguments, but got 3.
src/scheduled-commands/NotificationScheduledJob.ts(18,30): error TS2554: Expected 1 arguments, but got 3.
``` 

Which references a line where the `Searcher<TObject>.filter()` function is being used:

```typescript
await Booster.readModel(ExampleReadModel)
        .filter("timestamp", "<", dateNow)
```

It looks like there is a problem with the compiler, **which is somehow expecting the Array filter specification.** This does not make sense, because even the VS Code plugin know which filter I'm referring to:

![image](https://user-images.githubusercontent.com/24827940/109327397-32cdd880-7850-11eb-8730-9c03485e1828.png) 

## Expected behavior

To compile the application without this problem.

### Environment

- Booster version: [e.g. 0.8.2] `0.11.2`
- Node/npm version: [e.g. Node 8/npm 5] `v14.8.0`/`6.14.7`
- OS: [e.g. OSX 10.13.4, Windows 10] MacOS `11.1`
- Typescript: `3.7.5`

**Comment by AdrianLorenzoDev** [comment]
Okay, it seems like there is a `0.11.4` version available, and now new Booster versions on deploy downloads dependencies, which made me use the new version because of the `^` qualifier. I solved it by using the `filterOld` function.

**Comment by alvaroloes** [comment]
Gosh. We should avoid the `^` qualifier. I'm going to start removing them little by little
