### ISSUE TITLE
DynamoDB nested attributes 

### ISSUE THREAD

**Issue by adriangmweb** [boostercloud/booster#652]
# Bug Report

## Description

DynamoDB has a limitation when querying a nested attribute of an array, so let's say that we have the following schema.
```typescript
class CartItem {
  public constructor(public productId: UUID, public quantity: number) {}
}

class Cart {
  public constructor(
    readonly id: UUID,
    readonly cartItems: Array<CartItem>
  ) {}
```
And we want to use the new `GraphQL` filers to get all the carts that have the product with `id = "0a9c7881-1f1e-44cd-9e7d-cf1df886fcbd"`, knowing that there is at least one cart that meets that criteria.

So we will use the following query: 
```graphql
CartReadModels
  (cartItems: {
    includes: {
      productId: { eq: "0a9c7881-1f1e-44cd-9e7d-cf1df886fcbd" }
      quantity: { eq: 7 }
    }
  })
  ```

## Expected behavior

As we know that there is a Cart that has that product, we will get at least the given Cart.
```json
  "data": {
    "CartReadModels": [{
        "id": "957603c5-9dad-42be-a33a-438d85658c68",
        "cartItems": [
          {
            "productId": "0a9c7881-1f1e-44cd-9e7d-cf1df886fcbd",
            "quantity": 62976
          }
        ]
      }]
  }
}
  ```

## Current Behavior

The result of the query is empty, but there is at least a Cart that has a product with that id.
```json
  "data": {
    "CartReadModels": []
  }
}
  ```
## Possible Solution

There is not a solid solution for this as it's a known limitation of `DynamoDB` that doesn't allow filtering a `Map` within a `List`. **Yeah, I know**🤦🏻‍♂️ 

 [This is the AWS thread about it.](https://forums.aws.amazon.com/thread.jspa?messageID=585008#585008)

There is a _ workaround_ using the `contain` function, but then the value inside the filter `includes` **must be the exact same object** instead of just a property, and we won't be able to use the filters like `eq, ne, gt, etc`. 

Of course, there is also the option of just using a list of IDs and the filter by those IDs.

**Any ideas about it?**

### Environment
- Booster version: Version in development

**Comment by adriangmweb** [comment]
As a partial solution, I changed the `GraphQL` schema for arrays from: 
```graphql
input cartItemsPropertyFilter {
  includes: CartItemPropertyFilter
}

input CartItemPropertyFilter {
  productId: StringPropertyFilter
  quantity: NumberPropertyFilter
  and: [CartItemPropertyFilter]
  or: [CartItemPropertyFilter]
  not: CartItemPropertyFilter
}
```

to

```graphql
input cartItemsPropertyFilter {
  includes: JSONObject
}
```

Honestly, I'm not really happy with it as it adds limitations in security and type validations, also the user is not able to perform our great filters on the nested properties of `CartItems`, but if they happen to know what's the exact object inside the array they can filter it. 

Also, they can filter things like Arrays of Strings, which is something that might unblock people who want to have a `List` of ids. 
```graphql
input skusPropertyFilter {
  includes: String
}
```
So it's a way of being able to filter those properties in Dynamo.

**Comment by alvaroloes** [comment]
I think you found the right trade-off :clap:
