### ISSUE TITLE
Access denied for read models subscription

### ISSUE THREAD

**Issue by Moneyba** [boostercloud/booster#654]
I tried to authorize some roles in some read models but I am getting access denied error in GraphQL subscription.
It works fine when I use authorize 'all'.

**Comment by otoumas** [comment]
@Moneyba I have been able to connect successfully without the access denied problem. If you want we can take a look at it.
Have you tried connecting with wscat  [graphQl subscription with wscat](https://github.com/boostercloud/booster/tree/main/docs#subscribing-to-read-models)
