### ISSUE TITLE
Wrong graphqlUrl

### ISSUE THREAD

**Issue by Moneyba** [boostercloud/booster#680]
# Bug Report

## Current Behavior

The returned graphqlUrl is` https://<base_url>/<environment>/graphqlURL`

## Expected behavior

graphqlUrl should be ` https://<base_url>/<environment>/graphql`

### Environment

- Booster version: 0.10.0
- Node/npm version: Node 14
- OS: OSX 11.1

**Comment by NickSeagull** [comment]
I believe this has been fixed already, no @Moneyba ?

**Comment by AdrianLorenzoDev** [comment]
As @NickSeagull said, this has already been fixed. Thank you for your help, @Moneyba!
