### ISSUE TITLE
Unable to query a read model with a filter

### ISSUE THREAD

**Issue by carlosper88** [boostercloud/booster#802]
## Description

I've been trying to retrieve a read model by filtering with UUIDPropertyFilter object, but I haven't been able to. I know it can be done but in the docs it doesn't show any example of its usage

https://docs.booster.cloud/#/chapters/03_booster-architecture?id=querying-a-read-model

This is what I've tried

```
query {
  PostReadModels(campaignId: {operation: eq, values: ["071f63d1-3e86-42fc-9858-42a86b5b8c10"]}) {
    brandId
    content
    creatorId
    date
    description
    id
    rate
  }
}
```

But it returns an error:
`"message": "Operator \"operation\" is not supported",`

Same thing with "eq" instead of eq returns:
`"message": "Enum \"UUIDOperations\" cannot represent non-enum value: \"eq\". Did you mean the enum value \"eq\"?"`

I've also tried with:
`PostReadModels(campaignId: {eq, ["071f63d1-3e86-42fc-9858-42a86b5b8c10"]})`

But it also returns a syntax error

Is it possible to have this feature a bit more documented? Thanks!

**Comment by NickSeagull** [comment]
I believe you meant `PostReadModel`  (singular), but still the error is not very helpful. There's an ongoing PR to fix this behavior #785

**Comment by carlosper88** [comment]
@NickSeagull 
It is in plural, I want to filter all the post by the campaignId field. This is the schema (some fields have been removed for short):

PostReadModels(
   brandId: UUIDPropertyFilter, 
   campaignId: UUIDPropertyFilter, 
   content: StringPropertyFilter, 
   id: UUIDPropertyFilter): [PostReadModel]

**Comment by NickSeagull** [comment]
Then it is definitely a bug, I believe the PR I linked will fix it

**Comment by adriangmweb** [comment]
Hey @carlosper88, thanks for reporting! Unfortunately, complex filters are not working yet, until #785 gets merged. After that, you'll be able to use all those filters ;)
