### ISSUE TITLE
Improve error message when a user doesn't include the `*-infrastructure` package in `devDependencies`

### ISSUE THREAD

**Issue by javiertoledo** [boostercloud/booster#871]
While the generators now insert the corresponding `*-infrastrucure` package in the user's project `devDependencies`, the user could delete it and the CLI will fail with the error message from the `require`. The objective of this task is to generate a better error message, guiding the user to add the dependency to `devDependencies` by suggesting to run the command:

    yarn add -D <provider-package>-infrastructure

**Comment by ManasviGoyal** [comment]
can you please explain where do i have to add the error message?

**Comment by NickSeagull** [comment]
Hello @ManasviGoyal , thanks for jumping into the conversation! 😄 

In this case, there's already a check in the AWS package for this, but there aren't any in the other cloud provider packages. It'd be a matter of moving [this check from the AWS package](https://github.com/boostercloud/booster/blob/64c1dc984a602efbf54f2fc5b50c41d1b33d27db/packages/framework-provider-aws/src/index.ts#L110-L123) to the other provider packages.

As a bonus, you could try to abstract this into a function so all packages could benefit from it, but just adding the check also works. Thanks!! 🙏
