### ISSUE TITLE
Rename lint scripts in package.json files

### ISSUE THREAD

**Issue by glammers1** [boostercloud/booster#96]
Lint scripts were [changed](https://github.com/boostercloud/booster/pull/89#discussion_r429756647) to be `lint:check` and `lint:fix` in the `package.json` template for projects created by Booster. It may make sense to have the same for the Booster project. As Tai said, `those changes may also require refactoring some pipeline steps`.

**Comment by lucky-c** [comment]
Hi can I take this one?

Is this issue needs to update every `package.json` files that still call lint script using `fix-lint` and update it using better format that is `lint:fix` or `lint:check`? please CMIIW
