### ISSUE TITLE
[CLI] Error while calling 'boost nuke' - Region must be configured

### ISSUE THREAD

**Issue by LaiaPerez88** [boostercloud/booster#98]
**Description**
**Given** that I am a user with a booster app deployed

**When** I run `boost nuke`

**Then** I get the following error

![image](https://user-images.githubusercontent.com/10027992/82901971-a0ae4200-9f56-11ea-9e77-85add52a726a.png)

**Acceptance criteria**

- Check that the region has been correctly specified
- Nuke the application

**Comment by MYF95** [comment]
It seems all booster commands, not only `nuke`, related to AWS will have this issue if the region is not set.
This issue occurs in two scenarios:

## You are using your `~/.aws/credentials` default settings and do not have the region in `~/.aws/config` or in the credentials file itself

```
[default]
aws_access_key_id=...
aws_secret_access_key=...
```

In this case, we can add the region in any of both files:

### ~/.aws/credentials

```
[default]
aws_access_key_id=...
aws_secret_access_key=...
region=us-east-1
```
**or**
### ~/.aws/config
```
[default]
region=us-east-1
```

## You are not using your `~/.aws/credentials` default settings and do not have the region configured:

```
[default]
aws_access_key_id=...
aws_secret_access_key=...

[theam]
aws_access_key_id=...
aws_secret_access_key=...
```

`export AWS_PROFILE=theam` --> this way, we are using the credentials under [Theam], but when we do this it seems the default region that is defined in `~/.aws/config` is ignored, even if we try to define it was with the credentials file.

To solve this, we have to add the region specifically under the credentials file:
### ~/.aws/credentials
```
[default]
aws_access_key_id=...
aws_secret_access_key=...

[theam]
aws_access_key_id=...
aws_secret_access_key=...
region=us-east-1
```

**Comment by NickSeagull** [comment]
Right now Booster uses the `default` profile to deploy, and it would require to add some configuration parameters to select another one.

Definitely the region thing should be added to the docs
