### ISSUE TITLE
GraphQL: Commands with 2 or more fields of the same custom class throws an error

### ISSUE THREAD

**Issue by alvaroloes** [boostercloud/booster#986]
# Bug Report

## Current Behavior

The following code:
```typescript
class Address {
  city?: string
  street?: string
}

@Command(...)
class Person {
   constructor(
     public personalAdress: Address,
     public workAddress: Addrsss,
     ...
  ) {}
}
```
Will give an error when the GraphQL schema is generated saying:
`Error: Schema must contain uniquely named types but contains multiple types named "AddressInput"`

The problem goes away when there is only one field with type `Address`.

Note that this doesn't happen if instead of a command, it is a read model the one that has two fields with the same custom class type. 

## Expected behavior

No error should be thrown
Note that this doesn't happen if instead of a command, it is a read model the one that has two fields with the same custom class type. 

## Possible Solution

The reason is that, when generating GraphQL types for custom types, we have a check to avoid generating two GraphQL types with the same name. But that check seems to only be in place when generating ReadModels, but not Commands. 
It should be also there when generating mutations from commands
### Environment

- Booster version: [e.g. 0.21.5] 
- Node/npm version: [e.g. Node 17/npm 8]
- OS: OSX 10.13.4]

**Comment by jesusAlvSoto** [comment]
Fixed in PR #1002
